version: '3'
services:
  dbserver:
    build: ./docker/mysql
    image: spring-db:0.0.1
    restart: always
    environment:
      MYSQL_DATABASE: spring
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      MYSQL_ROOT_PASSWORD: spring_root
    ports:
    - "3314:3306"
    volumes:
    - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    - ./docker/mysql/conf.d:/etc/mysql/conf.d
    - ./log/mysql:/var/log/mysql

  app:
    build: .
    image: spring-app/boot:0.0.1
    depends_on:
    - dbserver
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    environment:
      JAR_TARGET: demo-0.0.1-SNAPSHOT.jar

volumes:
  mysql-db:
    driver: local